// Root layout for the Next.js client app.
// Applies global fonts, wraps the app in the SessionProvider so all pages
// have access to auth state, and renders the persistent Navbar.

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@odigo/ui/globals.css";
import { SessionProvider } from "@/lib/SessionContext";
import Navbar from "@/components/Navbar";


const fontSans = Geist({
  subsets: ["latin"],
  variable: "--font-sans",
})

const fontMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * The root layout rendered on every page.
 * Provides the HTML shell, global fonts, dark mode class, session context,
 * and a sticky Navbar above the main scrollable content area.
 *
 * @param children - The page component rendered inside the layout
 */
export default function RootLayout({
  children,}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fontSans.variable} ${fontMono.variable} font-sans antialiased dark`}
      >
      <SessionProvider>
        <div className="flex flex-col h-screen">
          <Navbar />
          {/* Main content fills remaining height and is independently scrollable */}
          <main className="flex-1 overflow-auto">
            {children}
          </main>
        </div>
      </SessionProvider>
      </body>
    </html>
  );
}
